export const personalInfo = {
  name: "Akhilesh Vangala",
  email: "sv3129@nyu.edu",
  phone: "+1 (646) 772 9856",
  location: "New York, NY",
  linkedin: "https://linkedin.com/in/akhilesh-nyu",
  github: "https://github.com/Akhilesh-Vangala",
};

export const education = [
  {
    degree: "Master of Science, Data Science",
    institution: "New York University, Courant Institute",
    period: "Aug 2025 – May 2027",
    gpa: "4.0",
    courses: "Advanced Programming for Data Science, Optimization & Computational Linear Algebra, Machine Learning with Small Data, Machine Learning, Big Data",
  },
  {
    degree: "B.Tech, Computer Science (AI & ML)",
    institution: "Gandhi Institute of Technology and Management",
    period: "Aug 2021 – Jul 2025",
    gpa: "3.9",
    courses: "Probability & Statistics, Applied Statistics, Linear Algebra, DBMS, Data Structures, Algorithms, Big Data Analytics, Machine Learning, AI Applications",
  },
];

export const skillColumns = [
  {
    label: "Languages",
    iconKey: "code",
    items: ["Python", "R", "Java", "JavaScript", "TypeScript", "SQL", "Bash"],
  },
  {
    label: "ML & Data",
    iconKey: "brain",
    items: ["PyTorch", "TensorFlow", "Hugging Face", "XGBoost", "LightGBM", "SHAP", "Optuna", "GNNs", "RAG", "PySpark", "Pandas", "scikit-learn"],
  },
  {
    label: "Infrastructure",
    iconKey: "server",
    items: ["FastAPI", "Redis", "Kafka", "PostgreSQL", "SQLite", "AWS", "ONNX", "TensorRT", "Git", "Linux", "Docker"],
  },
];

export const allExperience = [
  {
    type: "research",
    role: "Graduate Research Assistant",
    org: "NYU Rory Meyers College of Nursing",
    advisor: "Prof. Han Chen",
    period: "Apr 2026 – Present",
    location: "New York, NY",
    bullets: [
      "Extended the HiFiMAP genome-wide IBD mapping pipeline for survival outcomes by replacing the linear mixed model null with a Cox proportional hazards mixed-effects model, simulating time-to-event data for 5,000 individuals with 70% event rate and 30% censoring.",
      "Cross-validated kinship matrix handling across coxme and GMMAT by fitting matched Gaussian mixed models via REML on a 5,000 × 5,000 sparse kinship matrix, confirming variance components agreed within 0.25% and residual correlation reached 1.0.",
      "Integrated martingale residuals and projection matrix components into fast variance-component score testing, running genome scans across 254,145 chromosome 22 SNP positions to identify significant IBD segments.",
    ],
    tags: ["R", "Cox PH Model", "HiFiMAP", "WGS", "Genomics", "REML"],
  },
  {
    type: "research",
    role: "Graduate Research Assistant",
    org: "Hochwagen Lab, New York University",
    advisor: "Prof. Andreas Hochwagen",
    period: "Jan 2026 – Present",
    location: "New York, NY",
    bullets: [
      "Built a custom ribosomal DNA variant analysis pipeline over 54 whole-genome sequencing samples (~1B reads/sample), detecting 528K+ variants across 13,365 positions at 5,000x+ depth for schizophrenia patient-control analysis.",
      "Resolved a 40x depth-underestimation flaw in standard tools by designing a strand-aware pileup parser with 8-column base-by-strand counts, strand-balance artifact filtering, and true-depth allele frequencies, increasing calls by 67x.",
      "Automated Mann-Whitney U hypothesis testing, FDR correction, EHR phenotype correlation, data validation, and publication-ready visualizations across 18S, 5.8S, and 28S ribosomal RNA regions.",
    ],
    tags: ["Python", "WGS", "rDNA Variants", "Bioinformatics", "FDR", "Schizophrenia"],
  },
  {
    type: "work",
    role: "Software Engineer Intern",
    org: "Dascase Technologies Inc.",
    advisor: "",
    period: "May 2024 – Jul 2024",
    location: "Hyderabad, India",
    bullets: [
      "Built and maintained backend services and API-driven workflows using Python, FastAPI, SQL, Git, and production-oriented engineering practices.",
      "Developed automation scripts and internal tooling to improve reliability, simplify repeated tasks, and support cleaner data handling across service workflows.",
      "Strengthened service quality through debugging, logging, testing, observability, and performance-focused iteration across internal and client-facing systems.",
    ],
    tags: ["FastAPI", "Python", "SQL", "Git", "Backend", "REST APIs"],
  },
];

// ─── All projects with real GitHub URLs and Lucide icon keys ───
export const allProjects = [
  {
    id: "fraud",
    featured: true,
    title: "Fraud Detection & Customer Intelligence Platform",
    domain: "Security · Graph ML",
    iconKey: "shield",
    color: { from: "#6366f1", to: "#8b5cf6", bg: "#eef2ff", text: "#4338ca", border: "#c7d2fe", soft: "rgba(99,102,241,0.08)" },
    description: "Detects fraud and anomalous customer behavior across 500K+ daily transactions in real time — 94% accuracy, 85% false-positive reduction, sub-50ms latency. Uses graph neural networks to model transaction networks with SHAP-based explainable inference.",
    tags: ["PyTorch", "GNN", "GraphSAGE", "Kafka", "FastAPI", "Redis", "SHAP"],
    metrics: ["94% accuracy", "85% ↓ false positives", "<50ms latency"],
    github: "https://github.com/Akhilesh-Vangala/FraudDetectionPlatform",
    demo: "",
  },
  {
    id: "icu",
    featured: true,
    title: "ICU Vital Sign Deterioration Forecasting",
    domain: "Healthcare · Time Series",
    iconKey: "activity",
    color: { from: "#10b981", to: "#059669", bg: "#ecfdf5", text: "#065f46", border: "#a7f3d0", soft: "rgba(16,185,129,0.08)" },
    description: "Predicts ICU patient deterioration 6 hours ahead on 40K+ MIMIC-III records. Hybrid LSTM-ARIMA architecture with SHAP interpretability — 7.6% RMSE improvement over LSTM baseline and 14.7% over XGBoost.",
    tags: ["PyTorch", "LSTM", "ARIMA", "MIMIC-III", "SHAP", "Time Series"],
    metrics: ["7.6% RMSE ↑ vs LSTM", "14.7% ↑ vs XGBoost", "40K+ patients"],
    github: "https://github.com/Akhilesh-Vangala/ICUVitalSignForecasting",
    demo: "",
  },
  {
    id: "debris",
    featured: true,
    title: "Underwater Debris Detection",
    domain: "Computer Vision · Edge",
    iconKey: "waves",
    color: { from: "#0ea5e9", to: "#0284c7", bg: "#f0f9ff", text: "#0c4a6e", border: "#bae6fd", soft: "rgba(14,165,233,0.08)" },
    description: "Classifies underwater debris across 8 categories at 47 FPS on NVIDIA GPUs — 96.2% accuracy, 94.3% mAP. CSWin Transformer with TensorRT FP16 optimization for real-time deployment.",
    tags: ["CSWin Transformer", "PyTorch", "ONNX", "TensorRT", "FP16"],
    metrics: ["96.2% accuracy", "94.3% mAP", "47 FPS @ TensorRT"],
    github: "https://github.com/Akhilesh-Vangala/UnderwaterDebrisDetection",
    demo: "",
  },
  {
    id: "medseg",
    featured: true,
    title: "MedSeg LLM",
    domain: "Medical AI · LLM",
    iconKey: "scan",
    color: { from: "#f43f5e", to: "#e11d48", bg: "#fff1f2", text: "#881337", border: "#fecdd3", soft: "rgba(244,63,94,0.08)" },
    description: "Segments CT scans pixel-by-pixel at 93% IoU and auto-generates diagnostic reports using fine-tuned LLaMA-2. Cuts manual radiology reporting workload by 70%.",
    tags: ["Mask R-CNN", "LLaMA-2", "FastAPI", "CT Scans", "PyTorch"],
    metrics: ["93% IoU", "70% ↓ manual effort", "40% ↓ runtime"],
    github: "https://github.com/Akhilesh-Vangala/MedSegLLM",
    demo: "",
  },
  {
    id: "worldcoder",
    featured: false,
    title: "WorldCoder",
    domain: "Generative AI · 3D",
    iconKey: "globe",
    color: { from: "#f59e0b", to: "#d97706", bg: "#fffbeb", text: "#92400e", border: "#fde68a", soft: "rgba(245,158,11,0.08)" },
    description: "Zero-shot 4D scene editing in Blender. Give it two videos (start state and goal state) and it automatically generates the Blender code to transform one into the other — no training data required.",
    tags: ["GPT-4", "Blender API", "Python", "Code Gen", "LLM"],
    metrics: ["Zero-shot", "4D editing"],
    github: "https://github.com/Akhilesh-Vangala/WorldCoder",
    demo: "",
  },
  {
    id: "podpress",
    featured: false,
    title: "PodPressAI",
    domain: "NLP · RAG Pipeline",
    iconKey: "mic",
    color: { from: "#8b5cf6", to: "#7c3aed", bg: "#f5f3ff", text: "#4c1d95", border: "#ddd6fe", soft: "rgba(139,92,246,0.08)" },
    description: "Converts newsletters into podcast scripts end-to-end using RAG, semantic chunking, and optimized LLM inference. FastAPI and Redis backend handles 50+ newsletters daily with 35% faster generation than baseline.",
    tags: ["LangChain", "RAG", "FastAPI", "Redis", "TTS", "NLP"],
    metrics: ["50+ newsletters/day", "35% faster"],
    github: "https://github.com/Akhilesh-Vangala/PodPressAI",
    demo: "",
  },
  {
    id: "smartrent",
    featured: false,
    title: "SmartRent Manhattan",
    domain: "Predictive Analytics",
    iconKey: "building",
    color: { from: "#06b6d4", to: "#0891b2", bg: "#ecfeff", text: "#164e63", border: "#a5f3fc", soft: "rgba(6,182,212,0.08)" },
    description: "Predicts Manhattan rental prices across 3,539 listings with R² 0.92 and ~$8 average error. XGBoost over 49 engineered features, benchmarked against Random Forest and Linear Regression.",
    tags: ["XGBoost", "SHAP", "Python", "Feature Engineering", "Pandas"],
    metrics: ["R² = 0.92", "~$8 avg error", "49 features"],
    github: "https://github.com/Akhilesh-Vangala/Smart_Rent_Manhattan",
    demo: "",
  },
  {
    id: "chestxray",
    featured: false,
    title: "Chest X-Ray Multi-Disease Classifier",
    domain: "Medical Imaging · Multi-Label",
    iconKey: "stethoscope",
    color: { from: "#64748b", to: "#475569", bg: "#f1f5f9", text: "#1e293b", border: "#cbd5e1", soft: "rgba(100,116,139,0.08)" },
    description: "Classifies 14 thoracic diseases simultaneously across 112,120 NIH chest X-rays. ResNet50 with focal loss, MixUp augmentation, and GradCAM visualization — 0.82 mean AUC-ROC across all disease classes.",
    tags: ["ResNet50", "PyTorch", "Focal Loss", "GradCAM", "NIH Dataset"],
    metrics: ["0.82 AUC-ROC", "14 classes", "112K+ images"],
    github: "https://github.com/Akhilesh-Vangala/ChestXRayMultiDiseaseClassification",
    demo: "",
  },
];

export const hackathonBadges = [
  {
    name: "Claude Builder Hackathon",
    org: "Columbia × NYU",
    project: "Nexus",
    desc: "Research advisor matching via dense embedding similarity.",
    color: { from: "#6366f1", to: "#8b5cf6" },
    repo: "https://github.com/Akhilesh-Vangala/Nexus",
  },
  {
    name: "NVIDIA × Dell Hackathon",
    org: "NYU Center for Data Science",
    project: "Stain AI",
    desc: "Recommendation system for personalized AI pathology under competitive constraints.",
    color: { from: "#10b981", to: "#059669" },
    repo: "https://github.com/Akhilesh-Vangala/rec-sys-nvidia-hackathon",
  },
  {
    name: "Google Hackathon",
    org: "NYU Tandon",
    project: "NYC Street Fix",
    desc: "Urban infrastructure problem-solving with deployable solution design.",
    color: { from: "#f59e0b", to: "#d97706" },
    repo: "https://github.com/Akhilesh-Vangala/nyc-street-fix",
  },
];
